const alertStyle = {
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  smallmodalContent: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    padding: '20px',
    borderRadius: '8px',
    textAlign: 'center',
    justifyContent: 'space-around',
  },
  bigmodalContent: {
    display: 'flex',
    width: '90%',
    height: 'auto',
    minHeight: '60%',
    flexDirection: 'column',
    backgroundColor: 'white',
    padding: '20px',
    borderRadius: '8px',
    textAlign: 'center',
    justifyContent: 'space-around',
  },
  contentplace: {
    width: '100%',
    maxWidth: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  modalButtonPlace: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'row',
    paddingTop: '10px',
    backgroundColor: 'white',
    borderRadius: '8px',
    textAlign: 'center',
    justifyContent: 'space-around',
  },
  modalButton: {
    backgroundColor: 'white',
    border: '0',
    cursor: 'pointer',
    textAlign: 'center', 
    fontSize: '0.9rem',
    fontWeight: 'bold',
  },
  
};

export default alertStyle;